name: drawly
description: "Desenhe, adivinhe e se divirta como nunca"

publish_to: "none"

version: 0.42.0

environment:
  sdk: ^3.5.4

dependencies:
  drawing_board:
    path: packages/drawing_board
  drawly_core:
    path: packages/drawly_core
  drawly_design_system:
    path: packages/drawly_design_system
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4
  universal_platform: ^1.1.0
  uuid: ^4.5.1
  # TODO(Kevin): Remove this dependency
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/avatars/
