// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgQc76nm1LuGagpxQO6Ydm6d70j-qxmXQ',
    appId: '1:1017794696113:web:bbe5aa1383bbfd26756390',
    messagingSenderId: '1017794696113',
    projectId: 'remottely-com',
    authDomain: 'remottely-com.firebaseapp.com',
    storageBucket: 'remottely-com.appspot.com',
    measurementId: 'G-2T5T10HMVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV-wkEIzaiwlu2DEwH6eNPOacO_o89mgk',
    appId: '1:1017794696113:android:022a716580185522756390',
    messagingSenderId: '1017794696113',
    projectId: 'remottely-com',
    storageBucket: 'remottely-com.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwhPq6E7Q9e7RmWbvhwwOwcXQ6NdKHB04',
    appId: '1:1017794696113:ios:26ba78609df15738756390',
    messagingSenderId: '1017794696113',
    projectId: 'remottely-com',
    storageBucket: 'remottely-com.appspot.com',
    iosBundleId: 'com.remottely.drawly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwhPq6E7Q9e7RmWbvhwwOwcXQ6NdKHB04',
    appId: '1:1017794696113:ios:26ba78609df15738756390',
    messagingSenderId: '1017794696113',
    projectId: 'remottely-com',
    storageBucket: 'remottely-com.appspot.com',
    iosBundleId: 'com.remottely.drawly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-oPEUKcbfsMfOrX9C96_Tw3zquBL6cUk',
    appId: '1:1017794696113:web:8b6068daf1b6c817756390',
    messagingSenderId: '1017794696113',
    projectId: 'remottely-com',
    authDomain: 'remottely-com.firebaseapp.com',
    storageBucket: 'remottely-com.appspot.com',
    measurementId: 'G-3J7QFQ7VRF',
  );
}
